### ISSUE TITLE
Generating an Angular 4 Project

### ISSUE THREAD

**Issue by brndoko** [Hongbo-Miao/office-addin-angular#3]
I attempted to generate an Angular 4 Add-in by using the Angular CLI and then generating a manifest.  However, I continued to run into the "Cannot find name 'Office'" error when I attempted to do the Office.initialize().  What did you do to solve this?

Also, when I cloned your repo and did 'ng serve' the component is not appearing.  It just says 'Loading ...'

**Comment by hongbo-miao** [comment]
Hi @brandonkoch6 
For your first question, see this line https://github.com/Hongbo-Miao/office-addin-angular/blob/master/src/main.ts#L11, this is how I do it now.

Check [Michael's answer](https://stackoverflow.com/questions/43599187/cannot-find-name-office) on Stack Overflow.

And track https://github.com/angular/angular-cli/issues/6385

To know what I added in an initial Angular project, check https://github.com/Hongbo-Miao/office-addin-angular/commit/6a8756ed5a5f2eb6487baae9e4b6981b50c712db

For your second question, you should side load in your Excel, instead of opening http://localhost:4200/ in your browser.

**Comment by brndoko** [comment]
Hi @Hongbo-Miao 

Thanks for your response.  I've been trying to figure out how to work with the Angular CLI in an Office Add-in for the past day.

The line:

declare const Office: any;

Does not appear to work.  This is what makes the component never actually load.  Even if I side-load the xml manifest in Excel, the Add-in just shows a white screen that says "Loading...".

I cloned your repo exactly how it is and then ran:

npm install
ng serve
sideloaded the xml manifest in a shared network directory into Excel

Am I missing something?

**Comment by brndoko** [comment]
Update: @Hongbo-Miao 

When I made my own angular-cli and used the line:

declare const Office: any

It did work for sideloading in Excel.  Though it's still not working for your repo for me.  I'm not sure why.  Also, it still says 'loading' in the browser for both.  Were you able to find a way to get around this for browser support?  I was hoping to be able to debug various items in the browser.

**Comment by hongbo-miao** [comment]
Hmm, weird, which browser and version are you using?

**Comment by brndoko** [comment]
I'm using Chrome Version 58.0.3029.110 (64-bit).

The jasmine tests I ran worked fine in the browser.  Just actually loading it in the browser on its own when I do ng serve doesn't seem to work.

**Comment by hongbo-miao** [comment]
I cannot reproduce.. Have you seen this? https://github.com/Hongbo-Miao/office-addin-angular/issues/2
Maybe because of same reason?

What it the version of you Excel? Are you on Windows or macOS?

**Comment by brndoko** [comment]
I ended up working this out.

**Comment by s1728k** [comment]
hi brandonkoch6 

I am also facing the same problem you discussed.

how did you work it out
